function createfigure1(t_calculado,y_esperado,y_calculado)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 08-Jun-2021 12:58:29

% Create figure



